spring.application.name=sra-api

# Configuración de conexión a Supabase (Pooler IPv4)
spring.datasource.url=jdbc:postgresql://aws-0-ca-central-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.tpkonvfzagdmywbtugho
spring.datasource.password=uma_sra2026
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true

# Puerto del servidor
server.port=8080
springdoc.swagger-ui.path=/

# Configuración JWT (La clave debe tener al menos 256 bits codificados en Base64)
security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Expiración en milisegundos (86400000 = 24 horas)
security.jwt.expiration-time=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=va224100093@uma.edu.sv
spring.mail.password=kxlu datr jbqo bycp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Origen permitido para CORS (puedes poner * para desarrollo o la URL de tu frontend)
cors.allowed-origin=http://localhost:5173